from pydantic import Field
from pydantic import BaseModel
from uuid import UUID
from typing_extensions import TypedDict,Annotated
from typing import Optional, Any




class ChatRequest(BaseModel):
    user_id: UUID = Field(..., description="UUID of the user")
    message: str = Field(..., description="User's message")

class SQLQueryGeneratorRequest(BaseModel):
    user_id: UUID = Field(..., description="UUID of the user")
    question: str = Field(..., description="The natural language question")
    db_schema: Optional[str] = Field(None, description="The database schema, if known")
    table_name: Optional[str] = Field(None, description="The table name, if known")

class ChatResponse(BaseModel):
    response: Annotated[str | list | dict | Any, Field(..., description="Agent's response")]
    sql_query: Annotated[str | None, Field(None, description="SQL query generated by the agent")]

class TablesResponse(TypedDict):
    tables: Annotated[list[str], Field(..., description="List of table names")]


class ChatResumeRequest(BaseModel):
    user_id: UUID = Field(..., description="UUID of the user")
    decision: str = Field(..., description="The user's decision: approve or edit or reject")

