from pydantic import Field
from pydantic import BaseModel
from uuid import UUID



class ChatRequest(BaseModel):
    user_id: UUID = Field(..., description="UUID of the user")
    message: str = Field(..., description="User's message")

    

class ChatResponse(BaseModel):
    response: str = Field(..., description="Agent's response")
    sql_query: str | None = Field(None, description="SQL query generated by the agent")

class TablesResponse(BaseModel):
    tables: list[str] = Field(..., description="List of table names")