from pydantic import Field
from pydantic import BaseModel
from uuid import UUID
from typing_extensions import TypedDict,Annotated




class ChatRequest(TypedDict):
    user_id: Annotated[UUID, Field(..., description="UUID of the user")]
    message: Annotated[str, Field(..., description="User's message")]

    

class ChatResponse(BaseModel):
    response: Annotated[str, Field(..., description="Agent's response")]
    sql_query: Annotated[str, Field(None, description="SQL query generated by the agent")]

class TablesResponse(TypedDict):
    tables: Annotated[list[str], Field(..., description="List of table names")]